services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: https://gkgenerals.com
      NEXT_PUBLIC_APP_URL: https://gkgenerals.com
      NEXT_PUBLIC_APP_NAME: ${APP_NAME}
      NEXT_PUBLIC_APP_DESCRIPTION: ${APP_DESCRIPTION}
      FORCE_HTTPS: "false"
      NODE_ENV: "production"
      IMAGEKIT_PUBLIC_KEY: ${IMAGEKIT_PUBLIC_KEY}
      IMAGEKIT_PRIVATE_KEY: ${IMAGEKIT_PRIVATE_KEY}
      IMAGEKIT_URL_ENDPOINT: ${IMAGEKIT_URL_ENDPOINT}
      EVMAK_API_KEY: ${EVMAK_API_KEY}
      EVMAK_API_URL: ${EVMAK_API_URL}
      EVMAK_WEBHOOK_SECRET: ${EVMAK_WEBHOOK_SECRET}
    restart: unless-stopped
